---
# Update all required probe packages

# Add package signing keys
  - name: Add package signing keys
    apt_key:
      id: '{{item.id}}'
      url: '{{item.url}}'
      state: present
    loop:
     - { id: '7C4B94E8', url: 'https://bintray.com/user/downloadSubjectPublicKey?username=wand' }
     - { id: '2582E0C5', url: 'https://repos.influxdata.com/influxdb.key' }
    become: true
  - name: Add package signing keys (speedtest)
    apt_key:
      id: '379CE192D401AB61'
      keyserver: keyserver.ubuntu.com
      state: present
    become: true

  - name: Update sources list
    copy:
      src: files/{{ ansible_architecture }}-{{ ansible_distribution }}{{ ansible_distribution_version }}/{{item.src}}
      dest: "{{item.dest}}"
    loop:
     - { src: 'sources.list', dest: '/etc/apt/sources.list' }
     - { src: 'amplet.list', dest: '/etc/apt/sources.list.d/amplet.list' }
     - { src: 'speedtest.list', dest: '/etc/apt/sources.list.d/speedtest.list' }
    become: true

# should update below to be tidier and read from a file
  - name: Install 18.04 packages
    apt:
      deb: "{{ item }}"
    loop:
      - http://nz.archive.ubuntu.com/ubuntu/pool/main/n/nettle/libnettle6_3.4-1_amd64.deb
      - http://nz.archive.ubuntu.com/ubuntu/pool/main/n/nettle/libhogweed4_3.4-1_amd64.deb
      - http://nz.archive.ubuntu.com/ubuntu/pool/main/libe/libevent/libevent-2.1-6_2.1.8-stable-4build1_amd64.deb
      - http://security.ubuntu.com/ubuntu/pool/main/u/unbound/libunbound2_1.6.7-1ubuntu2.3_amd64.deb
    become: true

# should update below to be tidier and read from a file
  - name: Install packages <probes>
    when: "'probes' in group_names"
    apt:
      name:
        - amplet2-client
        - curl
        - iftop
        - iperf3
        - nmap
        - ntp
        - speedtest
        - traceroute
        - ufw
        - whois
      state: latest
      update_cache: yes
      autoremove: yes
    become: true
    notify: Restart Amplet

  - name: Install packages <endpoints>
    when: "'endpoints' in group_names"
    apt:
      name:
        - amplet2-client
        - curl
        - iftop
        - iperf3
        - nmap
        - ntp
        - speedtest
        - telegraf
        - traceroute
        - ufw
        - whois
        - apache2
        - php
        - libapache2-mod-php
      state: latest
      update_cache: yes
      autoremove: yes
    become: true
    notify:
      - Restart Amplet
      - Restart Apache

# NDT is a custom built off the latest source (since they don't publish a package)
# The dictionary maps the architecture variable to the filename
  - name: Install NDT
    apt:
      deb: "{{ packagesURL }}/ndt_3.7.0-1_{{ {'aarch64':'arm64.deb', 'armv7l':'armhf.deb', 'x86_64':'amd64.deb'}[ansible_architecture] }}"
      dpkg_options: force-overwrite
    become: true

# The amplet2 package isn't set for startup by default (since it needs configuring first).
  - name: Enable Amplet on startup
    service:
      name: amplet2-client
      enabled: yes
    become: true
    notify: Restart Amplet

# Disable apache2 on startup (since amplet could test to port 80)
  - name: Disable Apache on startup
    service:
      name: apache2
      enabled: no
    when: "'endpoints' in group_names"
    become: true

# Install custom scripts to /usr/local/bin (and strip extension)
  - name: Install custom scripts
    copy:
      src: files/{{item}}
      dest: /usr/local/bin/{{(item | splitext)[0]}}
      mode: 0755
    loop:
     - ss-pretty.py
     - ndttest.sh
    become: true