---
# From a starting OS installation, build a probe or endpoint

- hosts: probes:endpoints

  vars:
    rotateSSH: false			# rotate the SSH keys, see creds.yml
    rebuildFW: false			# rebuild FW rule by rule, rather than copying the rules files - use when rules have changed (or automate that somehow)
    hostname: "{% if 'probes' in group_names %}probe{% endif %}{{ inventory_hostname.split('.')[0] }}"
  vars_files:
    - vars/main.yml
    - vars/users.yml
    - vars/firewall.yml

  tasks:
    - import_tasks: tasks/creds.yml

    - name: Add remote control
      include_tasks: tasks/remote.yml
      when: "'probes' in group_names"

    - name: Remove remote control
      include_tasks: tasks/noremote.yml
      when: "'endpoints' in group_names"

    - import_tasks: tasks/packages.yml
    - import_tasks: tasks/firewall.yml
    - import_tasks: tasks/environment.yml
    - import_tasks: tasks/amplet.yml
    - import_tasks: tasks/rabbitClean.yml

    - name: Setup webserver <endpoints>
      include_tasks: tasks/webserver.yml
      when: "'endpoints' in group_names"

    - import_tasks: tasks/custom.yml

  handlers:
    - import_tasks: handlers/main.yml
